<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Market.Contracts\Market.Contracts.csproj" />
      <ProjectReference Include="..\Market.Domain\Market.Domain.csproj" />
      <ProjectReference Include="..\Market.Infrastructure\Market.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
      <PackageReference Include="MagicOnion" Version="6.0.0" />
      <PackageReference Include="MagicOnion.Server" Version="6.0.0" />
      <PackageReference Include="MagicOnion.Server.HttpGateway" Version="6.0.0" />
      <PackageReference Include="MediatR" Version="14.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
      <PackageReference Include="ServiceModel.Grpc.AspNetCore" Version="1.20.0" />
      <PackageReference Include="ServiceModel.Grpc.MessagePackMarshaller" Version="1.20.0" />
    </ItemGroup>

</Project>
